### ISSUE TITLE
 Inheritance from non-protocol, non-class type 'AnyGenerator<T>' 

### ISSUE THREAD

**Issue by djdance** [hossamghareeb/realmtasks#1]
just downloaded and it fails:

```
/Users/djdance/Downloads/realmtasks-master/RealmTasks/Pods/RealmSwift/RealmSwift/Results.swift:285:14: Inheritance from non-protocol, non-class type 'AnyGenerator<T>'
/Users/djdance/Downloads/realmtasks-master/RealmTasks/Pods/RealmSwift/RealmSwift/Results.swift:293:36: Use of undeclared type 'Element'
/Users/djdance/Downloads/realmtasks-master/RealmTasks/Pods/RealmSwift/RealmSwift/Results.swift:294:49: Use of undeclared type 'Element'
```

![cropimage](https://cloud.githubusercontent.com/assets/2269720/15836413/684190ba-2c3d-11e6-9ce8-b6fa6125c1ac.png)

**Comment by drewmccal** [comment]
I'm having this same issue.  Have you had any luck in resolving this?

**Comment by SketchySwift** [comment]
I am having the same problem too, the project i think needs to be updated

**Comment by karjaubayev** [comment]
I have the same issue too. I think a person who created does not care about this repository and issue...

**Comment by hossamghareeb** [comment]
@djdance @drewmccalmont  @HardcoreIOS  @altynbekkarjaubayev 
Hey all, 
sorry for my late reply. I have fixed the issues and now Realm and Xcode project are updated and work fine. Tested in Xcode 7.3.1
